spring:
  datasource:
    url: jdbc:h2:mem:kakaopay
    driver-class-name: org.h2.Driver
    username: kakaopay
    password:
  jpa:
    database: h2
  h2:
    console:
      enabled: true
      path: /kakaopay
csv:
  file:
    path: csv/input.csv